spring.application.name=SpringTest
# Configura o banco H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite ver o console do banco no navegador
spring.h2.console.enabled=true

# Mostra o SQL que o Spring está gerando no console (útil para aprender!)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update